package com.cr_d.passwordmanagerapp.ui

import com.cr_d.passwordmanagerapp.domain.value_objects.PasswordData

object PasswordRepository {
    val passwords = listOf(
        PasswordData(
            id = 1,
            account = "juan.perez@gmail.com",
            password = "Abcdef123!",
            hasLowerCase = true,
            hasUpperCase = true,
            hasNumbers = true,
            hasSpecials = true,
            application = "Gmail",
            url = "https://mail.google.com",
            creationDate = "2023-01-10",
            lastUpdate = "2024-05-02",
            securityScore = 8.50
        ),
        PasswordData(
            id = 2,
            account = "ana@empresa.com",
            password = "contraseñaSegura",
            hasLowerCase = true,
            hasUpperCase = true, // hay 'S' mayúscula en "Segura"
            hasNumbers = false,
            hasSpecials = false,
            application = "Work Mail",
            url = "https://mail.empresa.com",
            creationDate = "2022-06-15",
            lastUpdate = "2023-12-01",
            securityScore = 4.82
        ),
        PasswordData(
            id = 3,
            account = "usuario123",
            password = "onlylowercase",
            hasLowerCase = true,
            hasUpperCase = false,
            hasNumbers = false,
            hasSpecials = false,
            application = "LocalApp",
            url = "http://localhost:8080",
            creationDate = "2021-11-01",
            lastUpdate = "2021-11-01",
            securityScore = 2.94
        ),
        PasswordData(
            id = 4,
            account = "maria98",
            password = "MARIA2020",
            hasLowerCase = false,
            hasUpperCase = true,
            hasNumbers = true,
            hasSpecials = false,
            application = "BankPortal",
            url = "https://bank.example.com",
            creationDate = "2020-02-20",
            lastUpdate = "2022-02-20",
            securityScore = 4.42
        ),
        PasswordData(
            id = 5,
            account = "pedro@chat.com",
            password = "Ch@t_User2021",
            hasLowerCase = true,
            hasUpperCase = true,
            hasNumbers = true,
            hasSpecials = true,
            application = "ChatApp",
            url = "https://chat.example.com",
            creationDate = "2021-08-08",
            lastUpdate = "2024-01-10",
            securityScore = 7.85
        ),
        PasswordData(
            id = 6,
            account = "soporte@tienda.es",
            password = "Tienda#1",
            hasLowerCase = true,
            hasUpperCase = true,
            hasNumbers = true,
            hasSpecials = true,
            application = "ShopAdmin",
            url = "https://admin.tienda.es",
            creationDate = "2023-03-30",
            lastUpdate = "2023-09-05",
            securityScore = 7.21
        ),
        PasswordData(
            id = 7,
            account = "cliente77",
            password = "pass1234",
            hasLowerCase = true,
            hasUpperCase = false,
            hasNumbers = true,
            hasSpecials = false,
            application = "Ecommerce",
            url = "https://shop.example.com",
            creationDate = "2022-10-10",
            lastUpdate = "2022-10-10",
            securityScore = 3.0
        ),
        PasswordData(
            id = 8,
            account = "devteam",
            password = "DevTeam!",
            hasLowerCase = true,
            hasUpperCase = true,
            hasNumbers = false,
            hasSpecials = true,
            application = "CI Server",
            url = "https://ci.example.com",
            creationDate = "2019-05-01",
            lastUpdate = "2024-04-01",
            securityScore = 6.29
        ),
        PasswordData(
            id = 9,
            account = "alicia",
            password = "A1b2c3d4",
            hasLowerCase = true,
            hasUpperCase = true,
            hasNumbers = true,
            hasSpecials = false,
            application = "Notes",
            url = "https://notes.example.com",
            creationDate = "2024-02-14",
            lastUpdate = "2024-02-14",
            securityScore = 6.5
        ),
        PasswordData(
            id = 10,
            account = "sofia@red.com",
            password = "S0f!a#2022",
            hasLowerCase = true,
            hasUpperCase = true,
            hasNumbers = true,
            hasSpecials = true,
            application = "SocialNetwork",
            url = "https://social.example.com",
            creationDate = "2022-07-07",
            lastUpdate = "2024-06-20",
            securityScore = 8.82
        ),
        PasswordData(
            id = 11,
            account = "backup@server",
            password = "backup_server",
            hasLowerCase = true,
            hasUpperCase = false,
            hasNumbers = false,
            hasSpecials = true, // underscore considered special
            application = "Backup",
            url = "https://backup.example.com",
            creationDate = "2018-12-12",
            lastUpdate = "2020-12-12",
            securityScore = 3.52
        ),
        PasswordData(
            id = 12,
            account = "luis-app",
            password = "Lu1s-Acc",
            hasLowerCase = true,
            hasUpperCase = true,
            hasNumbers = true,
            hasSpecials = true, // dash is special
            application = "MobileApp",
            url = "https://app.example.com",
            creationDate = "2020-09-09",
            lastUpdate = "2023-11-11",
            securityScore = 7.0
        ),
        PasswordData(
            id = 13,
            account = "info@universidad.edu",
            password = "uni2024",
            hasLowerCase = true,
            hasUpperCase = false,
            hasNumbers = true,
            hasSpecials = false,
            application = "UniversityPortal",
            url = "https://universidad.edu",
            creationDate = "2024-01-01",
            lastUpdate = "2024-01-01",
            securityScore = 3.50
        ),
        PasswordData(
            id = 14,
            account = "manager",
            password = "M@nager2023!",
            hasLowerCase = true,
            hasUpperCase = true,
            hasNumbers = true,
            hasSpecials = true,
            application = "HR System",
            url = "https://hr.example.com",
            creationDate = "2023-04-04",
            lastUpdate = "2024-03-03",
            securityScore = 9.79
        ),
        PasswordData(
            id = 15,
            account = "operaciones",
            password = "OPER-ops",
            hasLowerCase = true,
            hasUpperCase = true,
            hasNumbers = false,
            hasSpecials = true,
            application = "Ops Dashboard",
            url = "https://ops.example.com",
            creationDate = "2021-01-15",
            lastUpdate = "2022-01-15",
            securityScore = 50.84
        ),
        PasswordData(
            id = 16,
            account = "test.user",
            password = "12345678",
            hasLowerCase = false,
            hasUpperCase = false,
            hasNumbers = true,
            hasSpecials = false,
            application = "Demo",
            url = "https://demo.example.com",
            creationDate = "2017-07-07",
            lastUpdate = "2018-07-07",
            securityScore = 10.0
        ),
        PasswordData(
            id = 17,
            account = "fernando",
            password = "Ferno_99",
            hasLowerCase = true,
            hasUpperCase = true,
            hasNumbers = true,
            hasSpecials = true, // underscore
            application = "Gaming",
            url = "https://gaming.example.com",
            creationDate = "2022-12-12",
            lastUpdate = "2023-12-12",
            securityScore = 7.55
        ),
        PasswordData(
            id = 18,
            account = "newsletter@media.com",
            password = "newsLETTER",
            hasLowerCase = true,
            hasUpperCase = true,
            hasNumbers = false,
            hasSpecials = false,
            application = "MediaCMS",
            url = "https://cms.media.com",
            creationDate = "2019-03-03",
            lastUpdate = "2021-03-03",
            securityScore = 4.2
        ),
        PasswordData(
            id = 19,
            account = "root",
            password = "R00t!#Secure",
            hasLowerCase = true,
            hasUpperCase = true,
            hasNumbers = true,
            hasSpecials = true,
            application = "ServerRoot",
            url = "ssh://192.168.0.1",
            creationDate = "2016-06-06",
            lastUpdate = "2024-07-07",
            securityScore = 9.20
        ),
        PasswordData(
            id = 20,
            account = "alumno2025",
            password = "alumno.2025",
            hasLowerCase = true,
            hasUpperCase = false,
            hasNumbers = true,
            hasSpecials = true, // dot considered special here
            application = "Campus",
            url = "https://campus.univ.edu",
            creationDate = "2025-01-10",
            lastUpdate = "2025-01-10",
            securityScore = 5.5
        )
    )
}