package com.cr_d.passwordmanagerapp.ui.screens

import android.util.Log
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.Button
import androidx.compose.material3.Checkbox
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp

import com.cr_d.passwordmanagerapp.domain.entities.PasswordGenerator
import com.cr_d.passwordmanagerapp.domain.value_objects.PasswordDataGeneration

@Composable
fun CreatePasswordScreen(innerPadding: PaddingValues){
    var hasLowerCase by remember { mutableStateOf(false) }
    var hasUpperCase by remember { mutableStateOf(false) }
    var hasNumbers by remember { mutableStateOf(false) }
    var hasSpecials by remember { mutableStateOf(false) }
    var passwordLength by remember { mutableStateOf(0) }
    var passwordError by remember { mutableStateOf("") }
    var isPasswordGenerated by remember { mutableStateOf(false) }
    var generatedPassword by remember { mutableStateOf("") }

    Column(Modifier
        .fillMaxSize()
        .padding(innerPadding), horizontalAlignment = Alignment.CenterHorizontally) {
        Text("Crear contraseña")
        Row (modifier= Modifier.fillMaxWidth()){
            CustomCheckbox("Minúsculas", hasLowerCase, { hasLowerCase=it }, Modifier.weight(1f) )
            CustomCheckbox("Mayúsculas", hasUpperCase, { hasUpperCase=it }, Modifier.weight(1f) )
        }
        Row{
            CustomCheckbox("Números", hasNumbers, { hasNumbers=it }, Modifier.weight(1f) )
            CustomCheckbox("Carácteres especiales", hasSpecials, { hasSpecials=it }, Modifier.weight(1f) )
        }

        CampoDecimal(passwordLength) { passwordLength=it }

        CreatePasswordButton(hasLowerCase, hasUpperCase, hasNumbers, hasSpecials, passwordLength, { passwordError=it}, { isPasswordGenerated=it}, {generatedPassword=it})
        ClearPasswordButton({ passwordError=it}, { isPasswordGenerated=it}, {generatedPassword=it})
        if(passwordError!= "") Text(passwordError)
        if(isPasswordGenerated) Text(generatedPassword)
    }
}

@Composable
fun CustomCheckbox(labelText: String, value: Boolean, onValueChange: (Boolean) -> Unit, modifier:  Modifier = Modifier ) {
    Row(
        modifier = modifier.padding(horizontal = 20.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Checkbox(
            checked = value,
            onCheckedChange = { onValueChange(!value) }
        )
        Text(labelText)
    }
}

@Composable
fun CampoDecimal(value: Int, onValueChange: (Int) -> Unit) {
    val textValue = value.toString()

    OutlinedTextField(
        value = textValue,
        onValueChange = { newText ->
            if (newText.matches(Regex("^\\d*\$"))) {
                val intValue = newText.toIntOrNull() ?: 0
                onValueChange(intValue)
            }
        },
        label = { Text("Valor decimal") },
        keyboardOptions = KeyboardOptions(
            keyboardType = KeyboardType.Number
        )
    )
}

@Composable
fun CreatePasswordButton(
    hasLowerCase: Boolean,
    hasUpperCase: Boolean,
    hasNumbers: Boolean,
    hasSpecials: Boolean,
    passwordLength: Int,
    onErrorChange: (String) -> Unit,
    isPasswordGenerated: (Boolean) -> Unit,
    generatedPassword: (String) -> Unit
) {
    val passwordDataGeneration = PasswordDataGeneration(hasLowerCase, hasUpperCase, hasNumbers, hasSpecials, passwordLength)
    val generator = PasswordGenerator(passwordDataGeneration)

    Column (modifier = Modifier.padding(top = 30.dp)) {
        Button(onClick = {
            try {
                val password = generator.generatePassword()
                isPasswordGenerated(true)
                generatedPassword(password)
            } catch (e: Exception) {
                Log.d("Error", e.message.toString())
                onErrorChange(e.message.toString())
            }
        }) {
            Text("Generar contraseña")
        }
    }
}

@Composable
fun ClearPasswordButton(
    onErrorChange: (String) -> Unit,
    isPasswordGenerated: (Boolean) -> Unit,
    generatedPassword: (String) -> Unit
){
    Column (modifier = Modifier.padding(top = 30.dp)) {
        Button(onClick = {
            try {
                generatedPassword("")
                onErrorChange("")
                isPasswordGenerated(false)
            } catch (e: Exception) {
                Log.d("Error", e.message.toString())
                onErrorChange(e.message.toString())
            }
        }) {
            Text("Resetear contraseña")
        }
    }
}